#!/usr/bin/env python3
"""Pin the LMS/HSS and XMSS/XMSS^MT vectors that are not NIST's.

NIST's ACVP-Server publishes LMS vectors (pinned with the other NIST files in
acvp_vectors.json.gz), but only for SHA-256/192 and only 87 of them, and it
publishes none for XMSS. SP 800-208 approves four hash families for each
scheme. These sources cover the rest, and each is labelled by where it came
from in every report, never presented as NIST's:

  pqc-kat     post-quantum-cryptography/KAT: ACVP-format LMS and XMSS
              vectors over every SP 800-208 family, "generated by an
              implementation independent of the one used by NIST"
  liboqs      open-quantum-safe/liboqs KATs: XMSS and XMSS^MT (every
              RFC 8391 and SP 800-208 set) and two-level HSS, from the
              reference implementations
  hash-sigs   cisco/hash-sigs test_testvector.c: RFC 8554 Appendix F's two
              HSS test cases, from an author of RFC 8554

Upstream text is stored verbatim, one bundle key per file, so the sha256 of
each entry equals the file's at the pinned commit; tools/doctor.py re-checks
every digest offline.

    python tools/pin_hbs_vectors.py            # fetch the pinned commits
    python tools/pin_hbs_vectors.py --check    # verify the bundle, no network
"""
import argparse
import gzip
import hashlib
import io
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools"))
import pin_edge_vectors as _E                                  # noqa: E402

VEC = REPO / "pq_verify" / "vectors"
BUNDLE = VEC / "hbs_vectors.json.gz"
MANIFEST = VEC / "HBS_MANIFEST.json"

SOURCES = {
    "pqc-kat": {
        "repo": "https://github.com/post-quantum-cryptography/KAT",
        "raw": "https://raw.githubusercontent.com/post-quantum-cryptography/KAT",
        "commit": "f238e347b1323344208eb316df9993c923334817",
        "date": "2025-04-05",
    },
    "liboqs": {
        "repo": "https://github.com/open-quantum-safe/liboqs",
        "raw": "https://raw.githubusercontent.com/open-quantum-safe/liboqs",
        "commit": "e6b9e783747536f34700aab4bd10718c2fecab3f",
        "date": "2026-09-29",
    },
    "hash-sigs": {
        "repo": "https://github.com/cisco/hash-sigs",
        "raw": "https://raw.githubusercontent.com/cisco/hash-sigs",
        "commit": "44e6c7de934c05942bf17cc819a81e765cfe67d7",
        "date": "2026-09-04",
    },
}

_LMS_SETS = [f"{fam}-{m}-{h}" for fam in ("SHA256", "SHAKE") for m in ("M24", "M32")
             for h in ("H5_H10", "H15", "H20", "H25")]
# Upstream misnames one directory (M25 for H25).
_LMS_KEYGEN = [s.replace("SHAKE-M32-H25", "SHAKE-M32-M25") for s in _LMS_SETS]
_XMSS_KEYGEN = [f"{f}-{n}-{h}" for f in ("SHA256", "SHAKE256") for n in ("N24", "N32")
                for h in ("H10", "H16", "H20")]
_XMSS_SIGGEN = [f"{f}-{n}-H10" for f in ("SHA256", "SHAKE256") for n in ("N24", "N32")]
_XMSS_SIGVER = ([f"SHA256-{n}-{h}" for n in ("N24", "N32") for h in ("H10", "H16", "H20")]
                + ["SHAKE256-N24-H10"]
                + [f"SHAKE256-N32-{h}" for h in ("H10", "H16", "H20")])
_OQS_XMSS = ([f"XMSS-{f}_{h}_{b}" for f, bs in (("SHA2", (192, 256, 512)),
                                                 ("SHAKE256", (192, 256)),
                                                 ("SHAKE", (256, 512)))
              for h in (10, 16, 20) for b in bs]
             + [f"XMSSMT-{f}_{h}-{d}_256" for f in ("SHA2", "SHAKE")
                for h, d in ((20, 2), (20, 4), (40, 2), (40, 4), (40, 8),
                             (60, 3), (60, 6), (60, 12))])
_OQS_LMS = ([f"LMS_SHA256_H{h}_W{w}" for h in (5, 10, 15, 20) for w in (1, 2, 4, 8)]
            + ["LMS_SHA256_H10_W4_H5_W8", "LMS_SHA256_H5_W8_H5_W8"])

FILES = (
    [("pqc-kat", f"LMS/LMS-keyGen-1.0-{s}/internalProjection.json") for s in _LMS_KEYGEN]
    + [("pqc-kat", f"LMS/LMS-sigGen-1.0-{s}/internalProjection.json") for s in _LMS_SETS]
    + [("pqc-kat", f"LMS/LMS-sigVer-{s}/internalProjection.json") for s in _LMS_SETS]
    + [("pqc-kat", f"XMSS/XMSS-{m}-{s}/{f}") for m, sets in (("keyGen", _XMSS_KEYGEN),
                                                             ("sigGen", _XMSS_SIGGEN),
                                                             ("sigVer", _XMSS_SIGVER))
       for s in sets for f in ("prompt.json", "expectedResults.json")]
    + [("liboqs", f"tests/KATs/sig_stfl/xmss/{n}.rsp") for n in _OQS_XMSS]
    + [("liboqs", f"tests/KATs/sig_stfl/lms/{n}.rsp") for n in _OQS_LMS]
    + [("hash-sigs", "test_testvector.c")]
)


def build(fetcher=None):
    return _E.build(fetcher or _E.fetch, sources=SOURCES, file_list=FILES)


def write(bundle, manifest):
    payload = json.dumps(bundle, sort_keys=True, separators=(",", ":")).encode()
    buf = io.BytesIO()
    with gzip.GzipFile(filename="hbs_vectors.json", mode="wb", fileobj=buf,
                       mtime=0, compresslevel=9) as fh:
        fh.write(payload)
    BUNDLE.write_bytes(buf.getvalue())
    MANIFEST.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")


def verify(bundle_path=BUNDLE, manifest_path=MANIFEST):
    return _E.verify(bundle_path, manifest_path)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="verify the pinned bundle against its manifest, offline")
    a = ap.parse_args(argv)
    if a.check:
        problems = verify()
        for p in problems:
            print(f"BLOCK  {p}")
        print("LMS/XMSS vectors sound" if not problems else f"{len(problems)} problem(s)")
        return 1 if problems else 0
    bundle, manifest = build()
    write(bundle, manifest)
    problems = verify()
    for p in problems:
        print(f"BLOCK  {p}")
    if problems:
        return 1
    print(f"pinned {len(bundle)} files -> {BUNDLE.relative_to(REPO)} "
          f"({BUNDLE.stat().st_size // 1024} KiB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
